// The procedural material library's invariants.
//
// The point of this suite is that the generators run for real, headless, on
// the vendored THREE — the same code path the browser takes, because there is
// only one. Nothing here mocks a texture. The claims under test are the three
// that make the library safe to ship against README.md's two-source rule: it
// loads with no DOM, its bytes are the same every run, and a surface class is
// never a source of colour.
import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import * as THREE from "../docs/vendor/three/three.module.min.js";
import {
  createMaterialLibrary, generateTextureSet, mulberry32, MATERIAL_CLASSES, LIBRARY_SEED,
} from "../docs/js/campus-materials.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = fs.readFileSync(path.join(ROOT, "docs/js/campus-materials.js"), "utf8");

/* Classes that carry maps. `glass` is the one documented exception. */
const MAPPED = MATERIAL_CLASSES.filter((c) => c !== "glass");

/* ------------------------------------------------------------ no DOM, ever */

test("module loads headless: no document, window or canvas is touched", () => {
  assert.equal(typeof globalThis.document, "undefined", "a DOM leaked into the test env");
  assert.equal(typeof globalThis.OffscreenCanvas, "undefined");
  /* The import at the top already proves it loads. This proves it also
     GENERATES without one — every class, not just the easy ones. */
  const lib = createMaterialLibrary(THREE);
  for (const cls of MATERIAL_CLASSES) {
    assert.ok(lib.get(cls, { color: 0x808080 }), `${cls} failed to build headless`);
  }
  lib.dispose();
});

test("no DOM API appears in the source at all", () => {
  for (const forbidden of ["document.", "OffscreenCanvas", "getContext", "createElement", "CanvasTexture"]) {
    assert.ok(!SOURCE.includes(forbidden), `source reaches for ${forbidden}`);
  }
});

/* --------------------------------------------------------------- the maps */

test("every mapped class returns a standard material with all three maps", () => {
  const lib = createMaterialLibrary(THREE);
  for (const cls of MAPPED) {
    const m = lib.get(cls, { color: 0x8a8378 });
    assert.equal(m.type, "MeshStandardMaterial", `${cls} is not a standard material`);
    for (const slot of ["map", "normalMap", "roughnessMap"]) {
      const t = m[slot];
      assert.ok(t, `${cls} has no ${slot}`);
      assert.equal(t.wrapS, THREE.RepeatWrapping, `${cls}.${slot} does not tile in S`);
      assert.equal(t.wrapT, THREE.RepeatWrapping, `${cls}.${slot} does not tile in T`);
      assert.ok(t.image.width >= 256 && t.image.width <= 512, `${cls}.${slot} odd tile size`);
      assert.equal(t.image.width, t.image.height, `${cls}.${slot} is not square`);
      assert.ok(t.image.data instanceof Uint8Array, `${cls}.${slot} is not generated bytes`);
    }
    assert.equal(m.map.colorSpace, THREE.SRGBColorSpace, `${cls} albedo is not sRGB`);
    assert.equal(m.normalMap.colorSpace, THREE.NoColorSpace, `${cls} normal must stay linear`);
    assert.equal(m.roughnessMap.colorSpace, THREE.NoColorSpace, `${cls} roughness must stay linear`);
  }
  lib.dispose();
});

test("glass is the documented exception: no maps, reflective, and it says so", () => {
  const lib = createMaterialLibrary(THREE);
  const g = lib.get("glass", { color: 0x9fb4c2 });
  assert.equal(g.type, "MeshStandardMaterial");
  assert.equal(g.map, null, "glass must not carry an albedo map");
  assert.equal(g.normalMap, null);
  assert.equal(g.roughnessMap, null);
  assert.ok(g.transparent && g.opacity < 1, "glass should read as glazing");
  assert.ok(g.roughness < 0.2, "glass must stay glossy enough to reflect the environment");
  assert.ok(g.envMapIntensity > 1, "glass leans on scene.environment for its read");
  lib.dispose();
});

/* ------------------------------------------------------------ determinism */

test("two independent libraries generate byte-identical buffers", () => {
  const a = createMaterialLibrary(THREE);
  const b = createMaterialLibrary(THREE);
  for (const cls of MAPPED) {
    const ta = a.textures(cls), tb = b.textures(cls);
    for (const slot of ["map", "normalMap", "roughnessMap"]) {
      assert.notEqual(ta[slot], tb[slot], `${cls}.${slot}: separate libraries must not share objects`);
      assert.deepEqual(
        Buffer.from(ta[slot].image.data), Buffer.from(tb[slot].image.data),
        `${cls}.${slot} is not reproducible`
      );
    }
  }
  a.dispose();
  b.dispose();
});

test("a different seed gives a different surface", () => {
  const a = generateTextureSet(THREE, "brick", { seed: LIBRARY_SEED });
  const b = generateTextureSet(THREE, "brick", { seed: LIBRARY_SEED + 1 });
  assert.notDeepEqual(Buffer.from(a.map.image.data), Buffer.from(b.map.image.data));
});

test("mulberry32 is a fixed sequence", () => {
  const r = mulberry32(1);
  const first = [r(), r(), r()];
  const again = mulberry32(1);
  assert.deepEqual([again(), again(), again()], first);
  for (const v of first) assert.ok(v >= 0 && v < 1, `${v} out of range`);
});

test("nothing in the library is stochastic", () => {
  assert.ok(!/Math\s*\.\s*random/.test(SOURCE), "the library reaches for a non-deterministic source");
  assert.ok(!/crypto|Date\s*\.\s*now|performance\s*\.\s*now/.test(SOURCE), "a non-reproducible input leaked in");
});

/* ----------------------------------------------------------------- caching */

test("one texture set per class: repeated get() shares GPU resources", () => {
  const lib = createMaterialLibrary(THREE);
  const a = lib.get("pavingConcreteUnit", { color: 0xb3b2a8 });
  const b = lib.get("pavingConcreteUnit", { color: 0x8a8378 });
  assert.notEqual(a, b, "each call gets its own material");
  for (const slot of ["map", "normalMap", "roughnessMap"]) {
    assert.equal(a[slot], b[slot], `${slot} was regenerated instead of shared`);
  }
  assert.equal(lib.textures("pavingConcreteUnit").map, a.map);
  lib.dispose();
});

test("a per-surface repeat clones the sampler but keeps the one upload", () => {
  const lib = createMaterialLibrary(THREE);
  const plain = lib.get("asphalt", { color: 0x5e6163 });
  const tiled = lib.get("asphalt", { color: 0x5e6163, repeat: [12, 40] });
  assert.notEqual(plain.map, tiled.map, "repeat must not be written onto the shared texture");
  assert.equal(plain.map.source, tiled.map.source, "the clone should share its pixels");
  assert.deepEqual([tiled.map.repeat.x, tiled.map.repeat.y], [12, 40]);
  assert.deepEqual([plain.map.repeat.x, plain.map.repeat.y], [1, 1], "the shared texture was mutated");
  const square = lib.get("asphalt", { repeat: 8 });
  assert.deepEqual([square.map.repeat.x, square.map.repeat.y], [8, 8]);
  lib.dispose();
});

/* ------------------------------------------- colour stays the caller's job */

test("albedo maps are grey: a class can never move a sourced colour off its hue", () => {
  const lib = createMaterialLibrary(THREE);
  for (const cls of MAPPED) {
    const d = lib.textures(cls).map.image.data;
    for (let i = 0; i < d.length; i += 4) {
      if (d[i] !== d[i + 1] || d[i] !== d[i + 2]) {
        assert.fail(`${cls} albedo texel ${i / 4} is coloured (${d[i]},${d[i + 1]},${d[i + 2]})`);
      }
    }
  }
  lib.dispose();
});

test("the caller's colour reaches the material untouched", () => {
  const lib = createMaterialLibrary(THREE);
  const m = lib.get("boardFormedConcrete", { color: 0x8a8378 });
  assert.equal(m.color.getHexString(), "8a8378");
  lib.dispose();
});

test("albedo variation is subtle: the maps modulate, they do not repaint", () => {
  const lib = createMaterialLibrary(THREE);
  for (const cls of MAPPED) {
    const d = lib.textures(cls).map.image.data;
    let sum = 0, n = 0;
    for (let i = 0; i < d.length; i += 4) { sum += d[i]; n++; }
    const mean = sum / n;
    assert.ok(mean > 150 && mean < 255, `${cls} albedo mean ${mean.toFixed(1)} would darken or blow out its colour`);
  }
  lib.dispose();
});

/* ---------------------------------------------------------------- content */

test("normal maps are unit-length and mostly face out", () => {
  const lib = createMaterialLibrary(THREE);
  for (const cls of MAPPED) {
    const d = lib.textures(cls).normalMap.image.data;
    for (let i = 0; i < d.length; i += 4 * 97) { // a stride, not every texel
      const x = d[i] / 255 * 2 - 1, y = d[i + 1] / 255 * 2 - 1, z = d[i + 2] / 255 * 2 - 1;
      const len = Math.hypot(x, y, z);
      assert.ok(Math.abs(len - 1) < 0.02, `${cls} normal texel ${i / 4} has length ${len.toFixed(3)}`);
      assert.ok(z > 0, `${cls} normal texel ${i / 4} points into the surface`);
    }
  }
  lib.dispose();
});

test("every class actually has structure — no flat tile ships", () => {
  const lib = createMaterialLibrary(THREE);
  for (const cls of MAPPED) {
    for (const slot of ["map", "normalMap", "roughnessMap"]) {
      const d = lib.textures(cls)[slot].image.data;
      let lo = 255, hi = 0;
      for (let i = 0; i < d.length; i += 4) { if (d[i] < lo) lo = d[i]; if (d[i] > hi) hi = d[i]; }
      assert.ok(hi - lo >= 6, `${cls}.${slot} is effectively flat (range ${hi - lo})`);
    }
  }
  lib.dispose();
});

test("foliage cuts its silhouette from the map's alpha", () => {
  const lib = createMaterialLibrary(THREE);
  const m = lib.get("foliage", { color: 0x5c7a3a });
  assert.ok(m.alphaTest > 0, "foliage must cut, not blend");
  assert.equal(m.side, THREE.DoubleSide, "leaf cards are seen from both faces");
  const d = m.map.image.data;
  let opaque = 0, clear = 0;
  for (let i = 3; i < d.length; i += 4) {
    if (d[i] > 200) opaque++;
    else if (d[i] < 40) clear++;
  }
  assert.ok(opaque > 0 && clear > 0, "the leaf mask is uniform — that is a rectangle, not a cluster");
  /* Every other class must stay fully opaque or it will sort against itself. */
  for (const cls of MAPPED.filter((c) => c !== "foliage")) {
    const a = lib.textures(cls).map.image.data;
    for (let i = 3; i < a.length; i += 4 * 53) {
      assert.equal(a[i], 255, `${cls} has a transparent texel`);
    }
  }
  lib.dispose();
});

test("standing seam is a real variant of the metal panel, not the same tile", () => {
  const lib = createMaterialLibrary(THREE);
  const flat = lib.get("metalPanel", { color: 0xb8bcc0 });
  const seam = lib.get("metalPanel", { color: 0xb8bcc0, standingSeam: true });
  assert.notEqual(flat.normalMap, seam.normalMap, "the seam option changed nothing");
  assert.notDeepEqual(
    Buffer.from(flat.normalMap.image.data), Buffer.from(seam.normalMap.image.data),
    "the standing seam has no relief"
  );
  assert.ok(seam.metalness > 0.5, "metal should read as metal");
  lib.dispose();
});

test("the maps tile: opposite edges of a wrapped texture agree", () => {
  const lib = createMaterialLibrary(THREE);
  for (const cls of MAPPED) {
    const t = lib.textures(cls).map;
    const S = t.image.width, d = t.image.data;
    let horiz = 0, vert = 0;
    for (let i = 0; i < S; i++) {
      horiz += Math.abs(d[(i * S) * 4] - d[(i * S + S - 1) * 4]);
      vert += Math.abs(d[i * 4] - d[((S - 1) * S + i) * 4]);
    }
    /* A seam shows up as a hard step along a whole edge; a tiling field's
       edges differ only as much as any two neighbouring rows do. */
    assert.ok(horiz / S < 40, `${cls} has a vertical seam (mean edge step ${(horiz / S).toFixed(1)})`);
    assert.ok(vert / S < 40, `${cls} has a horizontal seam (mean edge step ${(vert / S).toFixed(1)})`);
  }
  lib.dispose();
});

/* ------------------------------------------------------------------- misc */

test("an unknown class is a loud failure, not a silent grey box", () => {
  const lib = createMaterialLibrary(THREE);
  assert.throws(() => lib.get("marble"), /unknown material class/);
  assert.throws(() => generateTextureSet(THREE, "marble"), /unknown material class/);
  lib.dispose();
});

test("anisotropy is set, and overridable", () => {
  const a = createMaterialLibrary(THREE);
  assert.equal(a.textures("brick").map.anisotropy, 8);
  const b = createMaterialLibrary(THREE, { anisotropy: 16 });
  assert.equal(b.textures("brick").map.anisotropy, 16);
  a.dispose();
  b.dispose();
});

test("the class list covers the surfaces this campus is made of", () => {
  for (const cls of [
    "boardFormedConcrete", "smoothConcrete", "stucco", "metalPanel", "glass", "woodSlat",
    "pavingConcreteUnit", "brick", "asphalt", "decomposedGranite", "lavaRock", "foliage",
    "barkEucalyptus", "barkPine",
  ]) {
    assert.ok(MATERIAL_CLASSES.includes(cls), `${cls} is missing from the library`);
  }
});
